# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\tAiService\"/\n\nVoiceAudio\x12\x12\n\nspeaker_id\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\"O\n\x0ftranscribedText\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x12\n\nspeaker_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t2`\n\rTranscription\x12O\n\x16TranscriptionBiStreams\x12\x15.AiService.VoiceAudio\x1a\x1a.AiService.transcribedText(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VOICEAUDIO']._serialized_start=34
  _globals['_VOICEAUDIO']._serialized_end=81
  _globals['_TRANSCRIBEDTEXT']._serialized_start=83
  _globals['_TRANSCRIBEDTEXT']._serialized_end=162
  _globals['_TRANSCRIPTION']._serialized_start=164
  _globals['_TRANSCRIPTION']._serialized_end=260
# @@protoc_insertion_point(module_scope)
