# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\tAiService\"\x1f\n\x0fTtsSpeakRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x10TtsSpeakResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\x32O\n\x03Tts\x12H\n\x0bSpeakStream\x12\x1a.AiService.TtsSpeakRequest\x1a\x1b.AiService.TtsSpeakResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TTSSPEAKREQUEST']._serialized_start=24
  _globals['_TTSSPEAKREQUEST']._serialized_end=55
  _globals['_TTSSPEAKRESPONSE']._serialized_start=57
  _globals['_TTSSPEAKRESPONSE']._serialized_end=104
  _globals['_TTS']._serialized_start=106
  _globals['_TTS']._serialized_end=185
# @@protoc_insertion_point(module_scope)
